import React from "react";
import { BadgeCheck, Briefcase, Star } from "lucide-react";
import { Card, EmptyState } from "../components/ui";
import { useFetch } from "../api/AppContext";
import type { WorkerPassport } from "../api/client";

export default function PublicWorkerProfile({ workerId }: { workerId: string }) {
  const { data, loading, error } = useFetch<{ passport: WorkerPassport }>(`/workers/${workerId}/public-profile`);
  const profile = data?.passport;
  if (loading) return <div className="min-h-screen bg-sky-50 flex items-center justify-center text-slate-500">Loading professional passport...</div>;
  if (error || !profile) return <div className="min-h-screen bg-sky-50 flex items-center justify-center p-4"><EmptyState icon="⚠" title="Passport unavailable" description={error || "This worker profile is not available."} /></div>;
  return <main className="min-h-screen bg-sky-50 px-4 py-8"><div className="mx-auto max-w-xl space-y-4"><Card padding="lg" className="bg-navy text-white"><p className="text-xs uppercase tracking-wider text-sky-300">FixBuddy Professional Passport</p><h1 className="mt-2 text-3xl font-bold font-display">{profile.worker.name}</h1><p className="mt-1 text-slate-300">{profile.passport.skills[0]?.name || "Service professional"}</p><div className="mt-6 grid grid-cols-3 gap-3 text-center"><div><Briefcase className="mx-auto mb-1 h-5 w-5 text-sky-300" /><b className="text-xl">{profile.stats.totalJobs}</b><p className="text-xs text-slate-300">Jobs</p></div><div><Star className="mx-auto mb-1 h-5 w-5 text-amber-300" /><b className="text-xl">{profile.stats.rating.toFixed(1)}</b><p className="text-xs text-slate-300">Rating</p></div><div><BadgeCheck className="mx-auto mb-1 h-5 w-5 text-emerald-300" /><b className="text-xl">{profile.stats.verified ? "Yes" : "Pending"}</b><p className="text-xs text-slate-300">Verified</p></div></div></Card><Card padding="lg"><h2 className="font-semibold text-slate-900">About</h2><p className="mt-2 text-sm text-slate-600">{profile.passport.bio || "This professional has not added a bio yet."}</p><h2 className="mt-5 font-semibold text-slate-900">Skills</h2><div className="mt-2 flex flex-wrap gap-2">{profile.passport.skills.map((skill) => <span key={skill.id} className="rounded-full bg-emerald-50 px-3 py-1.5 text-sm text-emerald-800">{skill.name}{skill.verified ? " · Verified" : ""}</span>)}</div>{profile.badges?.length ? <><h2 className="mt-5 font-semibold text-slate-900">Badges</h2><div className="mt-2 flex flex-wrap gap-2">{profile.badges.map((badge) => <span key={badge} className="rounded-full bg-amber-50 px-3 py-1.5 text-sm text-amber-800">{badge}</span>)}</div></> : null}</Card></div></main>;
}
